---
- name: Respond to ServiceNow catalog request items
  hosts: all
  execution_strategy: parallel
  sources:
    - name: Listen on Service Now catalog events
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Enrich new REQ received from Service Catalog
      condition: event.payload is defined
      action:
        run_job_template:
          name: "EDA Enrich ServiceNow REQ"
          organization: Default
          post_events: true
          job_args:
            extra_vars:
              req_sys_id: "{{ event.payload.req_sys_id }}"
              req_number: "{{ event.payload.ritm_number }}"

    - name: Provision VM
      condition: event.enriched_event is defined
      action:
        run_job_template:
          name: "Demo Job Template"
          organization: Default
          job_args:
            extra_vars:
              req_sys_id: "{{ event.enriched_event.req_sys_id | default('undefined') }}"
              req_number: "{{ event.enriched_event.ritm_details[0].number.display_value | default('undefined') }}"






        # run_workflow_template:
        #   name: "EDA Multi Hypervisor Create and Config VM, Deploy Web App with Failure Paths Citrix"
        #   organization: "Infrastructure"
        #   job_args:
        #     extra_vars:
        #       vm_name: "{{ event.enriched_event.ritm_details[0].variables | selectattr('name', 'equalto', 'vm_name') | map(attribute='value') | join(',') }}"
        #       owner: "{{ event.user }}"
        #       env: "{{ event.enriched_event.ritm_details[0].variables | selectattr('name', 'equalto', 'env') | map(attribute='value') | join(',') }}"
        #       ticket_number: "{{ event.original_event }}"

