---
- name: Respond to ServiceNow catalog request items
  hosts: all
  execution_strategy: parallel
  sources:
    - name: Listen on Service Now catalog events
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Output ServiceNow Information
      condition: event.meta is defined
      action:
        debug:
          var: event.payload
