---
- name: Respond to ServiceNow catalog request items
  hosts: all
  execution_strategy: parallel
  sources:
    - name: Listen on Service Now catalog events
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Enrich new REQ received from Service Catalog
      condition: event.payload is defined
      action:
        run_job_template:
          name: "EDA Enrich ServiceNow REQ"
          organization: Default
          post_events: true
          job_args:
            extra_vars:
              req_sys_id: "{{ event.payload.req_sys_id }}"
              req_number: "{{ event.payload.ritm_number }}"

    - name: Provision Special Projects VM
      condition: event.business_purpose == "special_projects"
      action:
        run_job_template:
          name: "Provision Special Project VM"
          organization: Default
          job_args:
            extra_vars:
              vm_specific_variables: "{{ event.enriched_event.ritm_details[0].variables }}"
              req_number: "{{ event.enriched_event.ritm_details[0].number.value }}"
              requested_for_user: "{{ event.enriched_event.ritm_details[0].requested_for.display_value }}"

    - name: Provision Test VM
      condition: event.business_purpose == "testing"
      action:
        run_job_template:
          name: "Provision Test VM"
          organization: Default
          job_args:
            extra_vars:
              vm_specific_variables: "{{ event.enriched_event.ritm_details[0].variables }}"
              req_number: "{{ event.enriched_event.ritm_details[0].number.value }}"
              requested_for_user: "{{ event.enriched_event.ritm_details[0].requested_for.display_value }}"
